version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm i npm@latest -g
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build # 빌드
  post_build:
    commands:
      - aws s3 sync ./build s3://scsblog
